# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://jpanther.github.io/congo/docs/getting-started/

baseURL = "https://emiya-omega.github.io/"
defaultContentLanguage = "en"
title = "House of Eternity"
enableRobotsTXT = true
paginate = 10
summaryLength = 0

[params.author]
name = "Emiya-Omega"
image = "img/author.jpg"
headline = "Such a noob"
bio = "A little bit about me"
links = [
  { github = "https://github.com/emiya-omega" }
]
[outputs]
  home = ["HTML", "RSS", "JSON"]

[params]
  mainSections =['posts' , 'CPP' ]
  
[params.page.library]
  [params.page.library.css]
  [params.page.library.js]
    live2d-widget1 = "https://cdn.jsdelivr.net/npm/live2d-widget@3.1.4/lib/L2Dwidget.min.js"
    live2d-widget2 = "https://cdn.jsdelivr.net/npm/live2d-widget@3.1.4/lib/L2Dwidget.0.min.js"
    live2d-config = "/js/live2d_config.js"
